# Generated by Django 3.2.9 on 2021-11-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('sexuality', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=500)),
                ('profile_pic', models.CharField(max_length=200)),
            ],
        ),
    ]
