# Generated by Django 3.2.9 on 2021-11-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='age',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='persona',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NONBINARY', 'Non-Binary'), ('OTHER', 'Other')], default='OTH', max_length=9),
        ),
        migrations.AlterField(
            model_name='persona',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexuality',
            field=models.CharField(choices=[('STRAIGHT', 'Straight'), ('GAY', 'Gay'), ('BISEXUAL', 'Bisexual'), ('ASEXUAL', 'Asexual'), ('PANSEXUAL', 'Pansexual'), ('OTHER', 'Other')], default='OTH', max_length=9),
        ),
    ]
