# Generated by Django 3.2.9 on 2021-11-20 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_persona_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Nonbinary', 'Non-Binary'), ('Other', 'Other')], default='Other', max_length=9),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexuality',
            field=models.CharField(choices=[('Straight', 'Straight'), ('Gay', 'Gay'), ('Bisexual', 'Bisexual'), ('Asexual', 'Asexual'), ('Pansexual', 'Pansexual'), ('Other', 'Other')], default='Other', max_length=9),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('body', models.TextField()),
                ('dated_added', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='personas.persona')),
            ],
        ),
    ]
