# Generated by Django 3.2.9 on 2021-11-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20211120_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='profile',
        ),
    ]
