# Generated by Django 3.2.9 on 2021-11-11 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=3)),
                ('height', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NONBINARY', 'Non-Binary'), ('OTHER', 'Other')], default='OTH', max_length=9)),
                ('sexuality', models.CharField(choices=[('STRAIGHT', 'Straight'), ('GAY', 'Gay'), ('BISEXUAL', 'Bisexual'), ('ASEXUAL', 'Asexual'), ('PANSEXUAL', 'Pansexual'), ('OTHER', 'Other')], default='OTH', max_length=9)),
                ('occupation', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=500)),
                ('profile_pic', models.CharField(max_length=200)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
