# Generated by Django 3.2.9 on 2021-11-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
